name: arkitek_app
description: A Flutter app connecting architects with potential clients
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3  # Adjust to your version
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  animate_do: ^3.0.2
  equatable: ^2.0.5
  dio: ^5.8.0+1
  shared_preferences: ^2.2.1
  flutter_blurhash: ^0.8.2
  shimmer: ^3.0.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  file_picker: ^10.1.9
  go_router: ^14.8.0
  intl: ^0.19.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0  # Adjust to your version
  timeago: ^3.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_chat_ui: ^1.6.9
  uuid: ^4.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  lottie: ^3.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/Animation - 1749213060037.json

